name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  attestations: write
  contents: read
  id-token: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dive
        run: |
          DIVE_VERSION="0.13.1"
          curl -fOL "https://github.com/wagoodman/dive/releases/download/v${DIVE_VERSION}/dive_${DIVE_VERSION}_linux_amd64.deb"
          sudo apt install ./dive_${DIVE_VERSION}_linux_amd64.deb

      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        id: build
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          sbom: true
          provenance: true

      - name: Analyze image with dive
        run: |
          dive --ci "${{ fromJson(steps.build.outputs.metadata)['image.name'] }}@${{ fromJson(steps.build.outputs.metadata)['containerimage.digest'] }}" | tee -a $GITHUB_STEP_SUMMARY
